services:
  - type: web
    name: ponde-pesquisas-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push && npx prisma db seed
    startCommand: npm start
